{% set version = "1.4" %}

package:
  name: libftdi
  version: {{ version }}

source:
  url: https://www.intra2net.com/en/developer/libftdi/download/libftdi1-{{ version }}.tar.bz2
  sha256: ec36fb49080f834690c24008328a5ef42d3cf584ef4060f3a35aa4681cb31b74

build:
  number: 0
  skip: True  # [not linux]
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX -DSTATICLIBS:BOOL=OFF -DPYTHONBINDINGS=OFF -DBUILD_TESTS=OFF ..
    - make -j${CPU_COUNT}
    - make install

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - boost
    - libusb

test:
  commands:
    - libftdi1-config --libs
    - test -f $PREFIX/lib/pkgconfig/libftdi1.pc                 # [unix]
    - test -f $PREFIX/lib/pkgconfig/libftdipp1.pc               # [unix]
    - test -f $PREFIX/lib/cmake/libftdi1/LibFTDI1Config.cmake   # [unix]
    - test -f $PREFIX/lib/libftdi1.so.2                         # [unix]
    - test -f $PREFIX/lib/libftdi1.so                           # [unix]
    - test -f $PREFIX/include/libftdi1/ftdi.h                   # [unix]

about:
  home: https://www.intra2net.com/en/developer/libftdi/index.php
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'Library to talk to FTDI chips: FT232BM, FT245BM, FT2232C, FT2232D, FT245R, FT232H and FT230X including the popular bitbang mode.'

extra:
  recipe-maintainers:
    - hmaarrfk
